-- MySQL Script generated by MySQL Workbench
-- Thu Oct  3 13:06:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema feelback
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema feelback
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `feelback` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `feelback` ;

-- -----------------------------------------------------
-- Table `feelback`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feelback`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `email_users` VARCHAR(255) NOT NULL,
  `password_users` VARCHAR(255) NOT NULL,
  `create_at_users` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at_users` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_at_users` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_users`));


-- -----------------------------------------------------
-- Table `feelback`.`forms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feelback`.`forms` (
  `id_forms` INT NOT NULL AUTO_INCREMENT,
  `name_forms` VARCHAR(45) NOT NULL,
  `created_at_forms` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at_forms` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_at_forms` TIMESTAMP NULL DEFAULT NULL CURRENT_TIMESTAMP,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id_forms`),
  INDEX `FK_users_id_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `FK_users_id`
    FOREIGN KEY (`users_id`)
    REFERENCES `feelback`.`users` (`id_users`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feelback`.`packages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feelback`.`packages` (
  `id_packages` INT NOT NULL AUTO_INCREMENT,
  `create_at_packages` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `delete_at_packages` TIMESTAMP NULL DEFAULT NULL CURRENT_TIMESTAMP,
  `forms_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id_packages`),
  INDEX `FK_forms_id_idx` (`forms_id` ASC) VISIBLE,
  INDEX `FK_users_id_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `FK_forms_id`
    FOREIGN KEY (`forms_id`)
    REFERENCES `feelback`.`forms` (`id_forms`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_users_id`
    FOREIGN KEY (`users_id`)
    REFERENCES `feelback`.`users` (`id_users`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feelback`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feelback`.`questions` (
  `id_questions` INT NOT NULL AUTO_INCREMENT,
  `title_questions` VARCHAR(150) NOT NULL,
  `created_at_forms` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at_forms` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_at_questions` TIMESTAMP NULL DEFAULT NULL CURRENT_TIMESTAMP,
  `forms_id` INT NOT NULL,
  PRIMARY KEY (`id_questions`),
  INDEX `FK_forms_id_idx` (`forms_id` ASC) VISIBLE,
  CONSTRAINT `FK_forms_id`
    FOREIGN KEY (`forms_id`)
    REFERENCES `feelback`.`forms` (`id_forms`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feelback`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feelback`.`answers` (
  `id_answers` INT NOT NULL AUTO_INCREMENT,
  `value_answers` TINYINT NOT NULL,
  `created_at_answers` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at_answers` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delete_at_answers` TIMESTAMP NULL DEFAULT NULL CURRENT_TIMESTAMP,
  `questions_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id_answers`),
  INDEX `FK_questions_id_idx` (`questions_id` ASC) VISIBLE,
  INDEX `FK_users_id_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `FK_questions_id`
    FOREIGN KEY (`questions_id`)
    REFERENCES `feelback`.`questions` (`id_questions`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_users_id`
    FOREIGN KEY (`users_id`)
    REFERENCES `feelback`.`users` (`id_users`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
